In [30]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import linear_model


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

ModuleNotFoundError: No module named 'word2number'

In [2]:
# multivariate regression
# predicting home prices based on area bedrooms age of home
# price=m1*area+m2*bedrooms+m3*age+b


SyntaxError: invalid syntax (2585505552.py, line 1)

In [3]:
df = pd.read_csv("/kaggle/input/home-price-prediction-multi-feature/homeprices (2).csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
median_no= df.bedrooms.median().astype('int64')
median_no

4

In [9]:
df.bedrooms = df.bedrooms.fillna(median_no)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
#creating a linear regression class object
#then use fit method with independent variables: area bedrooms age
#dependent variable price
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [11]:
# M1 M2 M3
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [13]:
reg.intercept_

221323.00186540396

In [15]:
reg.predict([[3000,3,40]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

# Prediction of salary based on a) experience b) test score c) interview score

In [33]:
hw=pd.read_csv("/kaggle/input/hiring3/hiring.csv")
hw

experience  test_score  interview_score  salary($)
0         NaN         8.0                9      50000
1         NaN         8.0                6      45000
2         5.0         6.0                7      60000
3         2.0        10.0               10      65000
4         7.0         9.0                6      70000
5         3.0         7.0               10      62000
6        10.0         NaN                7      72000
7        11.0         7.0                8      80000

In [34]:
hw.experience=hw.experience.fillna(0)
hw

experience  test_score  interview_score  salary($)
0         0.0         8.0                9      50000
1         0.0         8.0                6      45000
2         5.0         6.0                7      60000
3         2.0        10.0               10      65000
4         7.0         9.0                6      70000
5         3.0         7.0               10      62000
6        10.0         NaN                7      72000
7        11.0         7.0                8      80000

In [35]:
median_no = hw.test_score.median()
median_no

8.0

In [36]:
hw.test_score = hw.test_score.fillna(median_no)
hw

experience  test_score  interview_score  salary($)
0         0.0         8.0                9      50000
1         0.0         8.0                6      45000
2         5.0         6.0                7      60000
3         2.0        10.0               10      65000
4         7.0         9.0                6      70000
5         3.0         7.0               10      62000
6        10.0         8.0                7      72000
7        11.0         7.0                8      80000

In [38]:
reg.fit(hw[['experience','test_score','interview_score']],hw['salary($)'])

LinearRegression()

In [39]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [40]:
reg.predict([[2,9,6]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [42]:
reg.predict([[12,10,10]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])